language: go

sudo: true

go:
  - "1.11.x"

env:
  - GO111MODULE=on

install:
  # Install `cover` and `goveralls` without `GO111MODULE` enabled so that we
  # don't download ct-woodpecker dependencies and just put the tools in our
  # gobin.
  - GO111MODULE=off go get golang.org/x/tools/cmd/cover
  - GO111MODULE=off go get github.com/mattn/goveralls
  - go install -v -mod=vendor ./...

before_script:
  - ct-test-srv -config ./test/config/cttestsrv.json &

script:
  - go vet -mod=vendor ./...
  - docker-compose run --use-aliases -v .:. ct-woodpecker go test -mod=vendor -v -race -covermode=atomic -coverprofile=coverage.out -tags=integration ./...
  - goveralls -coverprofile=coverage.out -service=travis-ci
  - docker-compose up -d
  - sleep 30s
  - docker-compose stop
  - docker-compose logs
